# Site settings
title: Glass Bead Labs
email: davclark@berkeley.edu
description: "Reflexive data science."
baseurl: ""
url: "http://bead.glass"
twitter_username: davclark
github_username: glass-bead-labs

# Build settings
markdown: kramdown
permalink: pretty
