# Site settings
title: Glass Bead Labs
email: tbd@nowhere.yet
description: "We do social measurement really, really well."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: tbd
github_username: glass-bead-labs

# Build settings
markdown: kramdown
permalink: pretty
