# Site settings
title: Glass Bead Labs
email: labs@bead.glass
description: "Reflexive data science."
baseurl: ""
url: "http://bead.glass"
twitter_username: GlassBeadLabs
github_username: glass-bead-labs
exclude: ["jobs.md"]

# Build settings
permalink: pretty
